version: '2'

services:
  angular: 
    build: angular-client
    ports: 
      - "80:80"
    #volumes:
    #    - .angular-client:/app

  express:
    build: express-server
    ports: 
      - "3000:3000"
    links: 
      - database

  database: 
    image: mongo
    ports:
      - "27017:27017"
