version: '2'

services:
  database: 
    image: mongo
    ports:
      - "27017:27017"

  express:
    build: express-server
    ports: 
      - "3000:3000"
    links: 
      - database


  angular: 
    build: angular-client
    ports: 
      - "80:80"
      - "3001:3001"
    #volumes:
    #    - .angular-client:/app
